# DevPilot Generated Project: WD-6
import gradio as gr

def hello(name):
    return f"Hello {name}! Welcome to DevPilot."

demo = gr.Interface(
    fn=hello,
    inputs=gr.Textbox(label="Your Name"),
    outputs=gr.Textbox(label="Greeting"),
    title="wd-6",
    description="Generated by DevPilot - AI-Powered SDLC Automation"
)

if __name__ == "__main__":
    demo.launch()
